### DISCUSSION TITLE
`proxy: reverse` to `proxy: redirect` question/ bug?

### DISCUSSION THREAD

**Discussion by aniel300** [euzu/tuliprox#122] [General]
if u change `proxy: reverse` to `proxy: redirect` it does take effect but if then change it back to `proxy: reverse` it doesn't apply/ take effect.

**Comment by euzu** [comment]
@aniel300 i have tested it and it works for me,  did you hit `save` ?

**Reply by aniel300** [reply]
yes i save the file and restart the container

**Reply by aniel300** [reply]
no matter what i do i cant get it to apply `proxy: reverse` to the m3u. it was working until i changed to `proxy: redirect`

**Reply by euzu** [reply]
@aniel300  i have tested this again and everything is working as expected.
You can look into the `api_proxy.yml` file to see the changes.
Are there any log outputs ? Errors ?

**Reply by aniel300** [reply]
no logs look fine. i even delete the db/ folder inside the data folder and resync the playlists. it won't mask/use the reverse stuff now. it did for a time but after changing it to redirect i cant get it to switch back. not sure if this is a cosmetic thing or not.

**Reply by aniel300** [reply]
are u using latest or beta?

**Reply by euzu** [reply]
You dont need to delete the db folder if you change user settings.

I have tested with beta and latest,  everything works as expected.

**Reply by euzu** [reply]
can you look into the `api_proxy.yml` ?

**Reply by aniel300** [reply]
yes it looks as follow:

```
server:
  - name: default 
    protocol: http
    host: 0.0.0.0
    http_port: 8901
    ttps_port: ''
    rtmp_port: ''
    timezone: America/New_York
    message: xxx
  - name: external
    protocol: http
    host: m3ufilter.xxx.top
    http_port: ''
    https_port: ''
    rtmp_port: ''
    timezone: America/New_York
    message: xxx
user:
  - target: a
    credentials:
      - {username: a, password: a, proxy: reverse, server: external}
  # - target: b
  #   credentials:
  #     - {username: a, password: a, proxy: reverse, server: external}          
  ```

**Reply by aniel300** [reply]
latest does work but not the beta one.

**Reply by euzu** [reply]
Ok first at all if you have the comments inside the file it means it is not saved. Because the comments are ignored when m3u-filter reads the file.

This means 2 things. This is not the file or  the file cant be changed due to access rights.

**Reply by aniel300** [reply]
are u referring to this?
```
  # - target: b
  #   credentials:
  #     - {username: a, password: a, proxy: reverse, server: external} 
  ```

**Reply by euzu** [reply]
yes

**Reply by aniel300** [reply]
that just means is commented out. this has nothing to do with access rights

**Reply by aniel300** [reply]
i took that out for good measure and same thing still happens. the fact that it works as indented with latest tells me there is something else at play with the beta one.

**Reply by euzu** [reply]
Yes but if you hit the `Save` button in the WebUI the comments are not written.

Maybe i am misunderstandiung you. I thought you change the proxy type in the WebUI. 

What exactly are you doing ? If you change it inside the `api_proxy.yml` file  and restart the container it should be reading it from the file.

**Reply by aniel300** [reply]
am not using the webui at the moment/ it is disabled. am making changes by opening and changing stuff directly into the files using vscode

**Reply by aniel300** [reply]
![image](https://github.com/user-attachments/assets/609289d6-7f9a-4b28-9611-e715282d8f98)

**Reply by euzu** [reply]
Than what you say does not make sense. `m3u-filter` is reading the config from the files.
if you write `redirect` it is redirect, if you write `reverse`  it is reverse.

Is it the right file ?

**Reply by aniel300** [reply]
yes

**Reply by euzu** [reply]
By the way try the webui for adding/modifying user. You dont need to restart if you do.

**Reply by aniel300** [reply]
am not using the webui at the moment/ it is disabled.

**Reply by aniel300** [reply]
> Than what you say does not make sense. `m3u-filter` is reading the config from the files. if you write `redirect` it is redirect, if you write `reverse` it is reverse.
> 
> Is it the right file ?

this is what am using but is not updating/ masking the end result m3u
```
user:
  - target: a
    credentials:
      - {username: a, password: a, proxy: reverse, server: external} 
```

**Reply by euzu** [reply]
i have created a config file with your information , everything works fine.  Can you please try the webui ?

**Reply by aniel300** [reply]
no difference. am getting this on the logs though, do u know what does it means? `024-11-20T15:10:26Z DEBUG m3u_filter::model::config] for input type m3u: username and password are ignored`

**Reply by euzu** [reply]
Yes, if you have a m3u source (input)  you only have a url which includes the credentials. username and password have no effect.
This is only a debug output. You can ignore it.

The log should only be visible when you define a username or password, in this case you found a bug (which has no effect).

**Reply by euzu** [reply]
@aniel300   when you hit Save on the WebUI does the file change ?  This is the question, it should remove all the comments.
If not this is not the file used by m3u-filter or m3u-filter does not have the access rights to read/write it.

**Reply by aniel300** [reply]
no no. the log error has nothing to with the project not switching back to `proxy: reverse`/masking the end result m3u when trying `proxy: redirect` but switching back to `proxy: reverse`. latest seems to work fine but i can't use latest.

**Reply by euzu** [reply]
@aniel300 can you test it with the 'beta'  version WebUI. 

When you hit Save on the WebUI does the file change ? This is the question, it should remove all the comments.
If not this is not the file used by m3u-filter or m3u-filter does not have the access rights to read/write it.

**Reply by aniel300** [reply]
i think i found the issue. it seems the beta. wants a new config structure, something like:
```
user:
- target: a
  credentials:
  - username: a
    password: a
    token: null
    proxy: redirect
    server: external
    epg_timeshift: null
```
and not
```
user:
  - target: a
    credentials:
      - {username: a, password: a, proxy: reverse, server: external} 
```
    
this confusion might have been cause but some discrepancy between the read me and the wiki...not the end of the world.

**Reply by euzu** [reply]
everything with   `property: null` is optional and can be skipped.

```yaml
user:
- target: a
  credentials:
  - username: a
    password: a
    token: null
    proxy: redirect
    server: external
    epg_timeshift: null
```
is exactly the same as:

```yaml
user:
- target: a
  credentials:
  - {username: a, password: a, proxy: reverse, server: external} 
```

It could be that your indentation was wrong. This has nothing to do with m3u-filter, this is the yaml format.
