### DISCUSSION TITLE
is there a way to separate live streams from movie and series?

### DISCUSSION THREAD

**Discussion by aniel300** [euzu/tuliprox#128] [General]
is there a way to separate live streams from movie and series? it seems when using `proxy: reverse` all streams including vod get this url structure `http://xxx/m3u-stream/xxx/xxx/xxx`. is it possible to separated it by type, something like for example:

`http://xxx/live/xxx/xxx/xxx`
`http://xxx/movie/xxx/xxx/xxx`
`http://xxx/series/xxx/xxx/xxx`
or 
`http://xxx/m3u-stream/live/xxx/xxx/xxx`
`http://xxx/m3u-stream/movie/xxx/xxx/xxx`
`http://xxx/m3u-stream/series/xxx/xxx/xxx`

**Comment by euzu** [comment]
@aniel300 this are different api's.  The m3u api does not make distincition between the stream types. The xtream api does.

**Reply by aniel300** [reply]
can u implement this for the m3u api?

**Comment by euzu** [comment]
@aniel300 rhis is not posible due to missing type information. There are no vod or seriea for m3u playlists.

**Reply by aniel300** [reply]
if i download the m3u from my  provider i believe they do separate it by /live/, /movie/ and /series/. u can't do anything with that?

**Comment by euzu** [comment]
@aniel300  yes for xtream sources, no for m3u playlists. Why do you need this?

**Reply by aniel300** [reply]
am importing using xc and exporting using m3u which then when i tried to use that m3u export on anything vod becomes part of the live channel stuff

**Reply by euzu** [reply]
yes because the m3u playlist does not support types. There is no player (as far as i know) which can handle types on m3u-playlists (because there is no type).

**Reply by euzu** [reply]
That is the reason why  you get only   live and  vod when you import m3u as xtream codes. The vod typing is guessing based on file extension.

**Reply by aniel300** [reply]
am confused. base on my understanding when i download a m3u plus from my provider it does separate live, from movies and series as follow. `.../user/pass/xxx`, `..../movie/...` and `.../series/...` so my question is is there a way to make ur proxy base on that logic to export it that way when using m3u export?

**Reply by euzu** [reply]
@aniel  i think you are confused between m3u playlist and xtream codes.

- m3u-playlist -> simple url which returns you a list of channels.
- xtream-codes -> is an api which returns you json files with the different content types. Each type has another api endpoint.


What you describe is only valid for xtream codes.  Yes you are right  when you access xtream codes api, the streams are seperated as you describe.

But m3u api delivers you only a plain - m3u  file.   This means you don't have types in it. Each entry is only a link/url (with some header lines before).

What could be the use case inside an m3u file to differentiate between stream types.

**Reply by aniel300** [reply]
when i download a m3u plus from my provider inside of it looks something like this
```
#EXTINF:0 CUID="xxx" tvg-name="xxx" tvg-logo="xxx" group-title="xxx",xxx
http://serverurl/user/pass/xxx

#EXTINF:0 CUID="xxx" tvg-name="xxx" group-title="xxx",xxx
http://serverurl/movie/user/pass/xxx

#EXTINF:0 CUID="xxx" tvg-name="xxx" group-title="xxx",xxx
http://serverurl/series/user/pass/xxx
```
i just want to make this clear. in addition, am using xc for import so this doesn't even matter. what am asking is that when i use `proxy: reverse` with m3u export that it separates live, from movies and tv shows as right now it doesn't and clients, etc. see movies and tv shows as live tv. ideally something like

`http://.../live/...`
`http://.../movie/...`
`http://.../series/...`
or 
`http://.../...`
`http://.../movie/...`
`http://.../series/...`
or 
`http://xxx/m3u-stream/live/xxx/xxx/xxx`
`http://xxx/m3u-stream/movie/xxx/xxx/xxx`
`http://xxx/m3u-stream/series/xxx/xxx/xxx`
or
`http://xxx/m3u-stream/xxx/xxx/xxx`
`http://xxx/m3u-stream/movie/xxx/xxx/xxx`
`http://xxx/m3u-stream/series/xxx/xxx/xxx`

**Comment by euzu** [comment]
@aniel300 what you describe is only specific for your provider. This is not defined by the m3u playlist format.

I think your provider has the information inside an database and creates links based on this information.

However i have created a beta image for you to test.  You dont need to fetch the new playlist, just start the new beta image and fetch the playlist.

**Reply by aniel300** [reply]
if i disabled/ use `proxy: redirect` then things work as expected. am using multiple providers so is not just specific to one provider

**Reply by aniel300** [reply]
am sorry i didn't see u created a beta image

**Comment by euzu** [comment]
@aniel300 i dont understand, did you test the beta image?

**Reply by aniel300** [reply]
sorry i didn't see u created a beta image for me

**Comment by euzu** [comment]
yes please test it

**Reply by aniel300** [reply]
seems to be working. will test more in deep soon. thank u very much

**Reply by aniel300** [reply]
i was testing more and channels dont see to be playing

**Comment by euzu** [comment]
@aniel300 which channels? All or only some? Any log output?

**Reply by aniel300** [reply]
[2024-12-02T22:51:37Z DEBUG m3u_filter::api::xtream_api] Target has no xtream output internal

**Comment by euzu** [comment]
This error only occurs with xtream api, not with m3u api. Are you really usind the m3u api?

**Reply by aniel300** [reply]
this is how i have it on my end
```
  targets:
    - name: internal
      output:
        - type: m3u               
          #filename: iptv.m3u
      sort:
        groups:
          order: asc
        channels:
          - {field: name, group_pattern: '^TR.:\s?(.*)', order: asc}
      filter: "!ALL_CHAN!"
    - name: external
      output:
        - type: m3u
          #filename: playlist.m3u
      sort:
        groups:
          order: asc
        channels:
          - {field: name, group_pattern: '^TR.:\s?(.*)', order: asc}
      filter: "!ALL_CHAN!"
```
```
 user:
- target: internal
  credentials:
    - {username: internal, password: internal, proxy: reverse, server: default}
- target: external
  credentials:
    - {username: external, password: external, proxy: reverse, server: external}
```

**Reply by aniel300** [reply]
i notice u removed some code as per: https://github.com/euzu/m3u-filter/commit/563c249fb61279aa2d10fbc3b86170f1b365b15e

**Reply by euzu** [reply]
Your output only supports m3u api, but yrou try to access it with xtream api. This does not work. You need to use the m3u api.

**Reply by aniel300** [reply]
> This error only occurs with xtream api, not with m3u api. Are you really usind the m3u api?

yes am getting the link directly from the m3u that i have open in the browser itself

**Comment by euzu** [comment]
Ok i found the problem,  but i am  not at my pc, i will create a new image tomorrow.

**Reply by aniel300** [reply]
ok i will wait until tomorrow. please do not forget and thank you very much.

**Reply by euzu** [reply]
i have pushed the beta image.  To get what you want you need to set options on target.

`options: {m3u_include_type_in_url: true, m3u_mask_redirect_url: true}`

```yaml
targets:
    - name: m3u
      publish: true
      filename:
      filter: "!MY_CHANNELS!"
      options: {ignore_logo: false, m3u_include_type_in_url: true, m3u_mask_redirect_url: true}
      output:
        - type: m3u
```

**Reply by aniel300** [reply]
u are on fire. what does this one does btw? `      publish: true` and `m3u_mask_redirect_url: true}`?

**Comment by euzu** [comment]
You asked for masking on redirect

**Reply by aniel300** [reply]
nice. let me try it right now and report back

**Reply by euzu** [reply]
i think `publish` is obsolete.

**Reply by aniel300** [reply]
where can i find the beta docker image?

**Reply by euzu** [reply]
Here:

![image](https://github.com/user-attachments/assets/faf23039-f9bb-4d19-885c-8371e32896b7)

**Reply by aniel300** [reply]
it is not masking when using `proxy: redirect` 😭

**Comment by euzu** [comment]
did you set the option?

**Reply by aniel300** [reply]
yes it looks as follow: 
```
  targets:
    - name: internal
      output:
        - type: m3u               
          #filename: iptv.m3u
      sort:
        groups:
          order: asc
        channels:
          - {field: name, group_pattern: '^TR.:\s?(.*)', order: asc}
      filter: "!ALL_CHAN!"
      options: {m3u_include_type_in_url: true, m3u_mask_redirect_url: true}     
    - name: external
      output:
        - type: m3u
          #filename: playlist.m3u
      sort:
        groups:
          order: asc
        channels:
          - {field: name, group_pattern: '^TR.:\s?(.*)', order: asc}
      filter: "!ALL_CHAN!"
      options: {m3u_include_type_in_url: true, m3u_mask_redirect_url: true}   
```
