### DISCUSSION TITLE
are logs senitized by default?

### DISCUSSION THREAD

**Discussion by aniel300** [euzu/tuliprox#153] [General]
is there a way to enabled or disabled logs sanitation base on admin server needs?
here is an example: `[2025-01-21T23:32:36Z ERROR m3u_filter::api::api_utils] Cant open stream http://***/live/***/71972.ts`

**Comment by euzu** [comment]
@aniel300 i have pushed a new beta image,  you can disable sanitizing  inside `config.yml`
```yaml
api: {host: 0.0.0.0, port: 8901, web_root: ./web}
working_dir: ./data
update_on_boot: false
log_sanitize_sensitive_info: false     <------------------
```

**Reply by aniel300** [reply]
perfect, thank you

**Reply by aniel300** [reply]
closing for now

**Reply by aniel300** [reply]
am getting this error: `[2025-01-24T08:26:45Z ERROR m3u_filter] M3uFilter error: cant read config file: web_auth: unknown field `threads`, expected one of `enabled`, `issuer`, `secret`, `userfile` at line 11 column 3`

**Reply by aniel300** [reply]
this new beta seems to have some breaking changes?: `[2025-01-24T08:29:56Z ERROR m3u_filter] M3uFilter error: cant read config file: sources[0].inputs[16].suffix: unknown field `options`, expected `field` or `value` at line 243 column 9`

**Comment by euzu** [comment]
@aniel300 yes you need a valid config. I have activated validation to avoid wrong config files.

You need to fix your config.

**Reply by aniel300** [reply]
did u update the readme or wiki?

**Comment by euzu** [comment]
Yes the config is described in the readme

**Reply by aniel300** [reply]
ok let me take a look at

**Reply by aniel300** [reply]
also i have a surprise for you

**Comment by euzu** [comment]
if you need help then please paste the anonymized config

**Reply by aniel300** [reply]
will do, thanks bud

**Reply by aniel300** [reply]
does this look ok to u?
```
#   sec  min   hour   day of month   month   day of week   year
schedules:
- schedule: "0  0  8  *  *  *  *"
web_ui_enabled: false
web_auth:
  enabled: false
  secret: very.secret.secret
  issuer: m3u_filter
  userfile: user.txt
  threads: 8
api: {host: 0.0.0.0, port: 8901, web_root: ./web}
working_dir: ./data
update_on_boot: true
reverse_proxy:
  stream:
    retry: true
    buffer:
      enabled: true   
      size: 1024
log_sanitize_sensitive_info: false
```
