### DISCUSSION TITLE
How to process input from cache? What does host and http_port affect in api-proxy.yml?

### DISCUSSION THREAD

**Discussion by kohanyirobert** [euzu/tuliprox#164] [Q&A] [answered]
Hey! Thanks for this tool. Just started using it. Config is pretty complex, but I managed to figure out things.

Two problems I came across:
1. When I run the tool a lot of times I got rate limited by my provider, is there a way to tell the tool to skip fetching inputs and work from cache? My use-case being while fiddling with what channels to keep and filter out I need re-run the tool a lot of times.
2. I configured host and http_port in api-proxy.yml ... but it hasn't got any effect. What's that for?

Thanks!

**Comment by euzu** [comment, marked as answer]
@kohanyirobert hi, 

There is no caching,  but what you can do is:  

- setup a m3u-filter  instance  with filter  'Group ~ ".*"'   on an xtream codes account
- then run an update. 


Now  take the first m3u-filter as your provider  and configure your real m3u-filter instance.

After finishing configuration you can shutdown the first instance.


`api_proxy.yml` is essential for accessing the api's.

You define how users access the api. The response urls are build from this informations.

when you set 
- ` protocol: http`   then `http_port` will be taken.
- ` protocol: https`   then `https_port` will be taken.

`rtmp_port` is currently useless.


In `api_proxy.yml`you can define multiple servers,  most time only two are enough   `default` for local network,  `external` for external access.

You can assign a server configuration to a user. The user can then access the api with the assigned server information.

**Reply by kohanyirobert** [reply]
Thanks for the double instance idea, great thinking :)

**Comment by euzu** [comment]
an example:

```yaml
server:
  - name: default
    protocol: http
    host: 192.168.9.3
    http_port: 80
    https_port:
    rtmp_port:
    timezone: Europe/Paris
    message: Welcome to m3u-filter
  - name: extern
    protocol: https
    host: m3u-filter.mydns.com
    http_port:
    https_port: 8443
    rtmp_port:
    timezone: Europe/Paris
    message: Welcome to m3u-filter
user:
  - target: pl1
    credentials:
      - {username: x3452, password: ztrhgrGZrt83hjerter, token: 4243234wer234er234, proxy: redirect, server: default}
      - {username: x3453, password: kljlkjorn87jfkhksdh, token: 43dfgerrt345345ss4, proxy: reverse, server: extern, epg_timeshift: -02:30}
```

**Reply by kohanyirobert** [reply]
Still I don't get it, but I saw this example. This is my "vague" idea of what this does:

host and http/https port combination only come into play when m3u-filter is used behind a proxy, no?
So if I set host to `somedomain.com` and port to `80` this assumes that _in front of_ m3u-filter there is a load-balancer/proxy (whatever you want to call it) that routes requests to m3u-filter. If a user access the m3u/xtream API using this `http://somedomain.com/m3u/username...` (etc.) and with proper/matchin username/password they will be able to access m3u-filter, otherwise not.

The confusion for me is this: even though I set host to some arbitrary address (10.0.0.1) and port (62123) m3u-filter will happily start up and be accessible *everywhere* since in the config I set 0.0.0.0 as the server bind address. So ... something like this works:

```
server:
  - name: default
    protocol: http
    host: 1.2.3.4
    http_port: 12345
    timezone: Europe/Budapest
    message: m3u-filter
user:
- target: sample_target
  credentials:
    - username: sampleuser
      password:  samplepass
```

This threw me off. User doesn't require a server field, since that's only for when behind a proxy (being an upstream service), but still the server block can't be omitted.

I think this piece of config mixes concepts up. At least for me. Great stuff btw.

**Reply by euzu** [reply]
Ok let me explain
You use it in a local network.
define only one server,  this is the so called `default`

Your m3u-filter is running on 192.168.1.100
This is the host.
Protocol ls http
http_port is  (if not changed in config.yml) 8901.

This information is responded to an iptvplayer when.it uses xtream codes api.

If you need external access too, you cab define a new server wlth https or http (up on you) with your domain name like  iptv.mydomain.com  and set  protocol.to.http or https and then set the port.

You need to assign a user the second server . If you do not its the default server.

Can you explain now what is mixed up in your opinion? If you have a better idea i am all ears.

**Reply by kohanyirobert** [reply]
> Can you explain now what is mixed up in your opinion?
I'm no networking expert, but when you say `If you need external access too, you cab define a new server` I'm confused a bit.

In `config.yml` with this settings:

```
api:
  host: 0.0.0.0
  port: 8091
```

I define that a server will run on the machine where I start m3u-filter and listen on all network interfaces for connections, on port 8091 (TCP).

Now if I have an `api-proxy.yml` with this:

```
server:
  - name: default
    protocol: http
    host: 1.2.3.4
    http_port: 12345
```

I'm not sure what to expect here. Even if I set this bogus config everything works. This is what confusing for me. If I set 1.2.3.4 as the host that does not mean if someone _externally_ wants to reach my m3u/xtream API then they will be able to do so by using http://1.2.3.4:12345/... because that's not how this works. I would expect the program reject a bogus config (if it can).

External access is provided by the fact that I start my app with a 0.0.0.0 bind address (or with a specific interface address), not because of the `api-proxy.yml` server config section.

Or it is possible that I'm entirely missing the point. I don't need this piece of config at all. For me it'd be enough the `user` block like this (without any server block at all):

```
user:
  - target: exampletarget
    credentials:
      - username: exampleuser
        password: examplepass
```

I know it's super difficult to maintain an open source project and deal with the likes of me :D so big kudos for you for doing exactly like that, so I hope my input helps you anyway to refine the software.

**Reply by euzu** [reply]
Ok i think there  is a misunderstanding.

The `config.yml` defines how m3u-filter  starts. Which ip it binds, which port it binds.  If you use 0.0.0.0  m3u-filter is reachable on all interfaces of your machine. 

The `api-proxy.yml` defines how user access m3u-url api. Not how the server itself starts.

The server config inside `api-proxy.yml` is used to build the urls in the playlists.
For example.

You have a user configured for reverse proxy.   m3u.-filter is running on  192.168.1.9.  

m3u-filter will now rewrite all urls, because  the url in the playlist is like `http://iptv-provider.com/get_php.....`.
But with reverse proxy mode on, the url needs to be like `http://192.168.1.9/get_php.....`.
That is defined inside `api-proxy.yml`

When you want external access and your domain name is `krobert.dyndns.com` 
then the urls should look like: `http://krobert.dyndns.com/get_php.....`.

Based on your comments i have now changed the configuration.
The next release wil also contain `path`configuration which makes it easier to configure `nginx` like proxies.


```yaml
server:
- name: default
  protocol: http
  host: 192.169.1.9
  port: '8901'
  timezone: Europe/Paris
  message: Welcome to m3u-filter
- name: external
  protocol: https
  host: m3ufilter.mydomain.tv
  port: '443'
  timezone: Europe/Paris
  message: Welcome to m3u-filter
  path: m3uflt
```

Now you can do `nginx`  configuration like
```config
   location /m3uflt {
      rewrite ^/m3uflt/(.*)$ /$1 break;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://192.169.1.9:8901/;
      proxy_ssl_session_reuse off;
      proxy_set_header Host $http_host;
      proxy_redirect off;
   }
```


I hope it is now clearer.
