### DISCUSSION TITLE
each input to a seperate target ?

### DISCUSSION THREAD

**Discussion by UserRS232** [euzu/tuliprox#184] [General]
first, thanks for this great tool!

I have 2 questions. If i define 2 input-sources and 2 targets, how do I get the input1 in target1 and the input2 in target2? I currently get input 1+2 in both targets and therefore have everything twice...

And, question 2. If i add the input source directly to "IPTV Smarters" APP, everthing works (with thousends of channels) ! If i add the m3u-filter xtream to the same app, i see the filtert list, but the stream wont work anymore. If i do the same with the Android APP "9xtream" everything works only when i choose "HLS (.m3u8)" in the Stream format settings, with Stream format "standard" the original stream works, but the m3u-filter stream wont.
Settings in m3u-filter to "redirect" . what could be the problem here?

**Comment by euzu** [comment]
@UserRS232 

You can define multiple sections with inputs/targets  combinations.
The inputs are all merged into the target definitions.

```yaml
sources:
- inputs:                                                                            <---- section 1
    - type: xtream
      url: 'http://fantastic.provider.xyz:8080'
      username: tvjunkie
      password: junkie.secret
    - type: xtream
      url: 'http://fantastic.provider2.xyz:8080'
      username: tvjunkie
      password: junkie.secret
  targets:
    - name: section_1
      output:
        - type: xtream
      filter: "!SECTION_1_FILTER!"
- inputs:                                                                     <---- section 2
    - type: m3u
      url: 'http://bubble.provider.xyz/get.php?username=tvjunkie&password=junkie.secret`
    - type: xtream
      url: 'http://gum.provider2.xyz:8080'
      username: tvjunkie
      password: junkie.secret
  targets:
    - name: section_2
      output:
        - type: xtream
      filter: "!SECTION_2_FILTER!"
```

Section 1 and 2 have different inputs and different outputs.


When you use redirect the resulting list should include the same urls like in the original list. You are bypassing m3u-filer and only downloading the playlist. You can do the following for testing. Define a m3u target and call it from the browser from m3u-filter.
Then you can compare the resulting playlist with the original.
