### DISCUSSION TITLE
Possible to link inputs to targets? How are you handing multiple provider input organization?

### DISCUSSION THREAD

**Discussion by nlitend1** [euzu/tuliprox#185] [General]
I'm running into an organizational issue. Say I want to  have input 1 go to target 1 and input 2 go to target 2. I'm not seeing how this is possible. Perhaps I've missing something or perhaps input can be used as a defining way to sort channels with regards to targets?

Also, with multiple inputs (say different providers/sources) with the same group names.... all of the channels from multiple providers get thrown together without organization/links/identification. Is there a way to address this? How are people handling this?

**Comment by euzu** [comment]
You can have multiple definitions of input and target configurations.

But a user can access only one target

You can

merge multiple inputs to one target with different outputs.

you can map one input to one target.

And you can repeat this.

I hope you understood what i am trying to say.

**Comment by nlitend1** [comment]
Could you please share an example of how a target can be limited to a single input when multiple inputs exist? In the sources.yml file I have 2 inputs, and i can target both m3u and xtream output types, but it seems those contain all inputs.

**Comment by euzu** [comment]
@nlitend1 for example you can use the mappping to add a suffix to entries from an i put. You should read the mapping part of the readme.

**Comment by euzu** [comment]
@nlitend1 here is an example

```yaml
sources:
- inputs:
  - name: input1
    type: xtream
    username: user_input1
    password: pwd_input1
    url: 'http://provider1.com'
  targets:
  - name: p1_xtream
    output:
      - type: xtream
      - type: hdhomerun
        username: xtr
        output: hdhr1
    filter: "!FILTER_1!"
- inputs:
  - name: input2
    type: m3u
    url: 'http://provider2.com/get.php?username=usr&password=secret'
  targets:
  - name: p2_m3u
    output:
      - type: m3u
    filter: "!FILTER_2!"
```

**Reply by nlitend1** [reply]
Yes, I've read over the mapping/templates section multiple times. Unfortunately it's hard for me to wrap my head around the regex stuff. That example certainly makes sense... but can FILTER_1 and FILTER_2 be more simply defined/linked to input names? 

If not, what I'm thinking is that the channel names may need to be modified in order to link them to a template. Sorry for my non-programming brain... just working through it.

**Comment by nlitend1** [comment]
Or wait... is p1_xtream automatically linked to only input1 because of the syntax of the config file? I have grouped all my inputs and targets. Maybe it's as simple as putting target 1 before input 2 in the config :)

**Comment by euzu** [comment]
Can you explain what you want to achieve ?

**Reply by nlitend1** [reply]
Separate targets based on input basically. At this point in time, my main function of m3u_filter is a rock solid proxy that can proxy my streams through my gluetun vpn. I am amazed at how solid it is. Nothing has worked better for that function. (It sounds like the future may allow more webui based filtering, but for now I still use a third party software (iptvboss) to fine tune my epg and playlists via as it’s been my go to for organization.) For now, I’d like to have this proxy function maintain provider organization and max connection limiting and then I can fine tune lists elsewhere. Once failover becomes part of m3u-filter this of course may all change.

**Comment by euzu** [comment]
@nlitend1 i have pushed an aarch-beta image 

the name is `m3u-filter-aarch64-beta:latest`

**Reply by nlitend1** [reply]
Thank you. Getting very late here. Gotta call it a day. Will keep you posted. Have a good one!

**Comment by euzu** [comment]
@nlitend1  you can organize your playlists completly with m3u-filter.
You need to master  regexp for filtering and  need to understand the powerfull mapping feature.

**Reply by nlitend1** [reply]
That is the ultimate goal for sure. :)  I’m all about minimizing points of failure and simplicity. I’m no where near that point atm though. 

So at this point is the only way to “link”/associate/identify a stream with its input modifying the name to include a suffix/prefix?  If so, can that be removed prior to reaching the client to keep things clean? 

Regardless of cli vs gui tools, I still feel it’s important to keep channels with the same group names (but separate sources/inputs) in separate groups (unless used for failover) and so I will be looking into doing that as well.

**Comment by euzu** [comment]
@nlitend1 you can define fine grained filter to discard or include based on regex.
You can regrpup based on regexp.
rename based on regexp.....

there are a lot of options and possibilities in mapping feature

**Comment by solohpgh** [comment]
This is how I would handle your initial question.  First two targets are splitting out your providers.  Third target, combines both providers and adds a prefix to the group names so that you can identify which provider.
(This should work with the current beta build)

source.yml
--
```
templates:
- name: ALL_CHAN
  value: 'Group ~ ".*"'
- name: FILTER_1
  value: 'input ~ "provider1"'
- name: FILTER2
  value: 'input ~ "provider2"'


sources:
- inputs:
  - name: provider1
    type: xtream
    username: user_p1
    password: pwd_p1
    url: 'http://provider1.com'

  - name: provider2
    type: xtream
    username: user_p2
    password: pwd_p2
    url: 'http://provider2.com'
  
  
  targets:
  - name: p1_xtream
    output:
      - type: xtream
    filter: "!FILTER_1!"  
  - name: p2_xtream
    output:
      - type: xtream
    filter: "!FILTER_2!"
  - name: pall_xtream
    output:
      - type: xtream
    filter: "!ALL_CHAN!"	
    mapping:
      - which_provider
```
	  
mapping.yml
--
```
mappings:
  templates:
	- name: PROV_1
	  value: 'input ~ "provider1"'
	- name: PROV_2
	  value: 'input ~ "provider2"'

  mapping:
    - id: which_provider
      match_as_ascii: true
      mapper:
        - pattern: "!PROV_1!"
          filter: 'Group ~ ".*"'
          prefix:
             group: '[P1] '
        - pattern: "!PROV_2!"
          filter: 'Group ~ ".*"'
          prefix:
             group: '[P2] '
```
