### DISCUSSION TITLE
SOCKS5 Proxy

### DISCUSSION THREAD

**Discussion by knylbyte** [euzu/tuliprox#233] [Ideas]
It would be great if you could implement a SOCKS5 proxy for requests. 
For example, if you want to run several gluetun containers behind a Traefik proxy for load balancing.

**Comment by euzu** [comment]
@knilly You want outgoing requests to the provider to go through the SOCKS5 proxy ?

**Reply by knylbyte** [reply]
Yes, that would be nice.

**Comment by euzu** [comment]
Something like this ? 

```yaml
socks5:
   host: proxy.example.com
   port: 1080
   username: optional_user
   password: optional_password
```

**Comment by euzu** [comment]
merged to master

- Added proxy configuration for all outgoing requests in `config.yml`. supported http, https, socks5 proxies.
```yaml
proxy:
  url: socks5://192.168.1.6:8123
  username: uname  # <- optional basic auth
  password: secret # <- optional basic auth
```
