### DISCUSSION TITLE
No reverse proxy streams operations after m3u-filter to Tuliprox migration

### DISCUSSION THREAD

**Discussion by nomandera** [euzu/tuliprox#274] [Q&A]
Hopefully you can help. After resurrecting my m3u-filter install and porting to the new Tuliprox project I cannot for the life of me make reverse proxy streams working again and I am out of ideas.

As far as I can tell everything works perfectly except that none of the reverse proxy channel streams from the m3u feed work.

If I load them in my browser I get `400` error code and in VLC just a generic error. The only sporadic error I see in an otherwise clean debug log is:

```
2025-05-26T08:56:16.495621945Z [2025-05-26T08:56:16Z DEBUG tuliprox::model::api_proxy] Could not find any target for user local
2025-05-26T08:56:16.495632805Z [2025-05-26T08:56:16Z DEBUG tuliprox::api::endpoints::m3u_api] Could not find any user local
```

My configuration is a collection of excerpts from the old and new documentation, a myriad of user posts and your stock example post.

I apolgise in advance as the most likely outcome of all this is PEBCAK.

My `compose.yml`

```
services:
    tuliprox:
        image: ghcr.io/euzu/tuliprox:latest
        working_dir: /app
        container_name: tuliprox
        user: ${PUID}:${PGID} # Requires root for initial run
        networks:
            - traefik
        ports:
            - 8901:8901
            - 8902:8902
        environment:
            - TZ=${TZ}
            - TULIPROX_HOST_IP=${TULIPROX_HOST_IP}
            - DOMAIN=${DOMAIN}
        volumes:
            - ${CONFIG}/tuliprox/tuliprox:/app/config # Place api-proxy.yml, config.yml, mapping.yml, source.yml here
            - /tmp:/app/config/data/tmp
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            # tuliprox webui & m3u
            - "traefik.http.services.tuliprox.loadbalancer.server.port=8901"
            - "traefik.http.routers.tuliprox.service=tuliprox"
            - "traefik.http.routers.tuliprox.entrypoints=websecure"
            - "traefik.http.routers.tuliprox.rule=Host(`tuliprox.${DOMAIN}`)"
            - "traefik.http.routers.tuliprox.middlewares=authelia@file, securityHeaders@file"
            # tuliprox hdhomerun
            - "traefik.http.services.tuliprox-hdhr.loadbalancer.server.port=8902"
            - "traefik.http.routers.tuliprox-hdhr.service=tuliprox-hdhr"
            - "traefik.http.routers.tuliprox-hdhr.entrypoints=websecure"
            - "traefik.http.routers.tuliprox-hdhr.rule=Host(`tuliprox-hdhr.${DOMAIN}`)"
            - "traefik.http.routers.tuliprox-hdhr.middlewares=authelia@file, securityHeaders@file"
            - "homepage.group=Downloaders"
            - "homepage.name=tuliprox"
            - "homepage.icon=tuliprox.svg"
            - "homepage.href=https://tuliprox.${DOMAIN}"
            - "homepage.description=Tuliprox IPTV proxy"
```

My `.env`

```
TULIPROX_HOST_IP=REDACTED_DOCKER_HOST_IP
```

My `api-proxy.yml`

```
server:

- name: default
  protocol: http
  host: ${env:TULIPROX_HOST_IP}
  port: '8901'
  timezone: Europe/London
  message: Welcome to Tuliprox

- name: external
  protocol: https
  host: tuliprox.${env:DOMAIN}
  port: '443'
  timezone: Europe/London
  message: Welcome to Tuliprox

user:

- target: iptv-org
  credentials:
  - username: local
    password: localsecret
    token: '77417'
    proxy: reverse
    server: default
    exp_date: 0
    max_connections: 0
    status: Active
    ui_enabled: true

  - username: external
    password: externalsecret
    token: '77418'
    proxy: reverse
    server: external
    exp_date: 0
    max_connections: 0
    status: Active
    ui_enabled: true

use_user_db: false


# To access the api (replace {} with credentials):

#     xtream      http://x.x.x.x/player_api.php?username={}&password={}
#     m3u         http://x.x.x.x/get.php?username={}&password={}
#     m3u         http://x.x.x.x/get.php?token={}
#     xtream      http://x.x.x.x/player_api.php?token={}
#     xtream      http://x.x.x.x:8901/player_api.php?username=user&password=secret&action=get_live_streams
#     hdhomerun   http://x.x.x.x:8902/lineup.json
```

My `config.yml`

```
threads: 0
api:
  host: 0.0.0.0
  port: 8901
  web_root: /app/web

working_dir: /app/config/data # Is this right? It seems to work but cannot find info on the logic of where to choose
backup_dir: /app/config/backup

custom_stream_response:
  channel_unavailable: /app/config/resources/channel_unavailable.ts
  user_connections_exhausted: /app/config/resources/user_connections_exhausted.ts
  provider_connections_exhausted: /app/config/resources/provider_connections_exhausted.ts

connect_timeout_secs: 10
user_access_control: false

video:
  web_search: 'https://www.imdb.com/search/title/?title={}'
  extensions:
  - mkv
  - avi
  - mp4
  - mpeg
  - divx
  - mov
  download:
    headers:
      Accept: video/*
      User-Agent: |
        Mozilla/5.0 (AppleTV; U; CPU OS 14_2 like Mac OS X; en-us) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
      Accept: video/*
    directory: /app/config/downloads
    organize_into_directories: false
    episode_pattern: .*(?P<episode>[Ss]\d{1,2}(.*?)[Ee]\d{1,2}).*

schedules:
- schedule: 0 0  4/23  *  *  *
  targets: []

messaging:
  notify_on: []

log:
  sanitize_sensitive_info: false
  log_active_user: true
  log_level: debug

update_on_boot: false  # best not to hammer upstream during testing

web_ui:
  enabled: true
  user_ui_enabled: true
  path:
  auth:
    enabled: true
    issuer: tuliprox
    secret: ef9ab256a8c0abe5de92c2e05ca92baa810472ab702ff1674e9248308ceeec92
    userfile: user.txt

reverse_proxy:
  stream:
    retry: true
    buffer:
      enabled: true
      size: 1024
    forced_retry_interval_secs: 10

  cache:
    enabled: true
    size: 1GB
    dir: /app/config/cache
  resource_rewrite_disabled: false

hdhomerun:
  enabled: true
  devices:
  - name: hdhr1
```

My `mapping.yml`

```
mappings:
  templates:
    - name: bbc
      value: 'Title ~ "^BBC.*"'
    - name: documentary
      value: '(Group ~ ".*Documentary.*" OR Group ~ ".*Outdoor.*")'
    - name: entertainment
      value: 'Group ~ ".*Entertainment.*"'
    - name: pluto_tv
      value: '(Title ~ ".*Pluto TV.*") AND NOT(Title ~ ".*Sports.*")'
    - name: business
      value: 'Group ~ ".*Business.*"'

  tags:
    - name: quality
      captures:
        - quality
      concat: '|'
      prefix: ' [ '
      suffix: ' ]'
    - name: year
      captures:
        - year
      concat: '|'
      prefix: ' [ '
      suffix: ' ]'

  mapping:
    - id: iptv-org
      match_as_ascii: true
      mapper:
        - pattern: "!bbc!"
          attributes:
            group: 'BBC'
        - pattern: "!documentary!"
          attributes:
            group: 'Documentary'
        - pattern: "!entertainment!"
          attributes:
            group: 'Entertainment'
        - pattern: "!pluto_tv!"
          attributes:
            group: 'Pluto TV'
        - pattern: "!business!"
          attributes:
            group: 'News'
```

My `source.yml`

```
templates:
- name: not_red_button
  value: 'NOT (Title ~ "(?i).*red button.*")'
- name: not_low_resolution
  value: 'NOT (Title ~ "(?i).*\(360p|240p\).*")'
- name: all_channels
  value: 'Title ~ ".*"'
- name: final_channel_lineup
  value: '!all_channels! AND !not_red_button! AND !not_low_resolution!'
sources:
- inputs:
  - name: iptv-org
    type: m3u
    url: https://iptv-org.github.io/iptv/countries/uk.m3u
    suffix:
      field: title
      value: '(iptv-org)'
  targets:
  - name: iptv-org
    output:
      - type: xtream
      - type: m3u
        filename: iptv.m3u
      - type: hdhomerun
        username: local
        device: hdhr1
    filter: "!final_channel_lineup!"
    options: {ignore_logo: false, share_live_streams: true}
    sort:
      groups:
        order: asc
      channels:
        - { field: name,  group_pattern: '^DE.*',  order: asc }
    mapping:
      - iptv-org
```

**Comment by euzu** [comment]
@nomandera 

i see some problems in your config

-    forced_retry_interval_secs: 10  !!! DO NOT USE !!! it forces a connection terminaton every 10 seconds, this is onyl for testing reconnect feature !!!

- working_dir: /app/config/data   -->  working_dir: /app/data
- backup_dir: /app/config/backup --> backup_dir: /app/backup
- directory: /app/config/downloads --> directory: /app/downloads
- dir: /app/config/cache --> dir: /app/cache

I hope you changed the secret 
- ef9ab256a8c0abe5de92c2e05ca92baa810472ab702ff1674e9248308ceeec92

- you have twice   Accept: video/*  in headers

- you have uk list but sort channels by de  { field: name, group_pattern: "^DE.*", order: asc }

If you run in server mode you dont need
- filename: iptv.m3u    , which is useless unless you use the file manually in other context.


I have used your config and adjusted it to the latest beta.

`config.yaml`

```yaml
threads: 0
api:
  host: 0.0.0.0
  port: 8901
  web_root: ${env:TULIPROX_HOME}/web
working_dir: ${env:TULIPROX_HOME}/data
backup_dir: ${env:TULIPROX_HOME}/backup
custom_stream_response_path: ${env:TULIPROX_HOME}/resources
connect_timeout_secs: 10
user_access_control: false

video:
  web_search: "https://www.imdb.com/search/title/?title={}"
  extensions:
    - mkv
    - avi
    - mp4
    - mpeg
    - divx
    - mov
  download:
    headers:
      Accept: video/*
      User-Agent: |
        Mozilla/5.0 (AppleTV; U; CPU OS 14_2 like Mac OS X; en-us) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
    directory: ${env:TULIPROX_HOME}/downloads
    organize_into_directories: false
    episode_pattern: .*(?P<episode>[Ss]\d{1,2}(.*?)[Ee]\d{1,2}).*

schedules:
  - schedule: 0 0  4/23  *  *  *
    targets: []

messaging:
  notify_on: []

log:
  sanitize_sensitive_info: false
  log_active_user: true
  log_level: debug

update_on_boot: false # best not to hammer upstream during testing

web_ui:
  enabled: true
  user_ui_enabled: true
  path:
  auth:
    enabled: true
    issuer: tuliprox
    secret: 9..........................................................................
    userfile: user.txt

reverse_proxy:
  stream:
    retry: true
    buffer:
      enabled: true
      size: 1024

  cache:
    enabled: true
    size: 1GB
    dir: ${env:TULIPROX_HOME}/cache
  resource_rewrite_disabled: false

hdhomerun:
  enabled: true
  devices:
    - name: hdhr1

```

`mapping.yml`
```yaml
mappings:
  templates:
    - name: bbc
      value: 'Title ~ "^BBC"'
    - name: documentary
      value: '(Group ~ "(Documentary|Outdoor)")'
    - name: entertainment
      value: 'Group ~ "Entertainment"'
    - name: pluto_tv
      value: '(Caption ~ "Pluto TV") AND NOT(Caption ~ "Sports")'
    - name: business
      value: 'Group ~ "Business"'

  mapping:
    - id: iptv-org
      match_as_ascii: true
      mapper:
        - filter: "!bbc!"
          script: |
            @Group = "BBC"
        - filter: "!documentary!"
          script: |
            @Group = "Documentary"
        - filter: "!entertainment!"
          script: |
            @Group = "Entertainment"
        - filter: "!pluto_tv!"
          script: |
            @Group = "Pluto TV"
        - filter: "!business!"
          script: |
            @Group = "News"
```

`source.yml`

```yaml
templates:
  - name: not_red_button
    value: 'NOT (Title ~ "(?i).*red button.*")'
  - name: not_low_resolution
    value: 'NOT (Title ~ "(?i).*\(360p|240p\).*")'
  - name: all_channels
    value: 'Title ~ ".*"'
  - name: final_channel_lineup
    value: "!all_channels! AND !not_red_button! AND !not_low_resolution!"
sources:
  - inputs:
      - name: iptv-org
        type: m3u
        url: https://iptv-org.github.io/iptv/countries/uk.m3u
        suffix:
          field: title
          value: "(iptv-org)"
    targets:
      - name: iptv-org
        output:
          - type: xtream
          - type: m3u
            filename: iptv.m3u
          - type: hdhomerun
            username: local
            device: hdhr1
        filter: "!final_channel_lineup!"
        options: { ignore_logo: false, share_live_streams: true }
        sort:
          groups:
            order: asc
          channels:
            - { field: name, group_pattern: "^DE.*", order: asc }
        mapping:
          - iptv-org
```

When is now update the playlist and make a  curl call 

curl "http://localhost:8901/player_api.php?username=local&password=localsecret&action=get_live_streams"

i get the live stream list
