### DISCUSSION TITLE
Difficulty getting Tivimate to accept proxied EPG

### DISCUSSION THREAD

**Discussion by kyle-greenholt** [euzu/tuliprox#286] [Q&A]
I have configured an Xtream input and corresponding target in tuliprox. However, when I add the Xtream target from tuliprox to Tivimate, it fails to load the EPG with the following message:

> Failed to update EPG from "hostname.domain" at 6/4/25 06:30 PM. Make sure EPG URL is correct and check your Internet connection.

A few interesting behaviors:
 - When I use the Xtream target from tuliprox in Televizo, the EPG loads without issue.
 - When I add the Xtream provider directly to Tivimate, it loads the EPG without issue.
 - When I add a different EPG like `https://open-epg.com/files/unitedstates1.xml` as the EPG source in tuliprox, Tivimate loads the EPG without issue.

This tells me that there something happening within tuliprox specifically with the full provider EPG that is breaking Tivimate's EPG loading process.

Has anyone else encountered this issue? Any suggestions to resolve it?

`source.yml`:

```yaml
templates:
- name: ALL_CHAN
  value: 'Group ~ ".*"'
sources:
- inputs:
    - type: xtream
      persist: './playlist_{}'
      name: providername
      url: 'PROVIDER_URL'
      epg:
        sources:
          - url: "EPG_URL"
      username: username
      password: password
      headers:
        User-Agent: "TiviMate/5.1.5 (Android 9)"
        Accept-Encoding: gzip
      options: {xtream_skip_vod: true, xtream_skip_series: true}
  targets:
    - name: all_channels
      output:
        - type: xtream
      filter: "!ALL_CHAN!"
      options: {ignore_logo: false, share_live_streams: true}
```

`api-proxy.yml`:

```yaml
server:
- name: default
  protocol: https
  host: hostname.domain
  port: '443'
  timezone: America/Los_Angeles
  message: Welcome
user:
- target: all_channels
  credentials:
  - username: username
    password: password
    proxy: reverse
    server: default
```
