### DISCUSSION TITLE
Provide Server Proxy details by Playlist

### DISCUSSION THREAD

**Discussion by adamsdavis572** [euzu/tuliprox#32] [Ideas]
Im using m3u-filter in reverse proxy mode and its working really well. Thanks very much. 

I have an additional feature that would be useful. I would like to access the m3u-filter proxy on 2 different URLs ie m3u-filter.example.com and m3u-filter.local.example.com. This is necessary because i have an ISP that only offers CGNAT and i want to be able to access the service outside of my house as well as inside. i therefore have to use a VPS - this is the entry point for m3u-filter.example.com. when at home i dont want to route via VPS so have a different address. 

Would it be possible to add server proxy details at Playlist level? This would allow me to support this configuration but simply using different user credentials for internal url vs external urls.

**Comment by euzu** [comment]
@adamsdavis572  i will try to find time this weekend,  i am currently very busy.

İ will think about a solution, maybe playlist or user based.

**Reply by adamsdavis572** [reply]
brilliant thank you

**Comment by euzu** [comment]
@adamsdavis572 i  have pushed the branch [feature/api_proxy_multiple_serverinfo](https://github.com/euzu/m3u-filter/tree/feature/api_proxy_multiple_serverinfo).

Can you test it?

You need to change the `api-proxy.yml` like:


```yaml
server:
  - name: default 
    protocol: http
    host: 192.168.0.3
    http_port: 80
    https_port: 443
    rtmp_port: 0
    timezone: Europe/Paris
    message: Welcome to m3u-filter
  - name: external
    protocol: http
    host: my_external_domain.com
    http_port: 80
    https_port: 443
    rtmp_port: 0
    timezone: Europe/Paris
    message: Welcome to m3u-filter
user:
  - target: pl1
    credentials:
      - {username: x3452, password: ztrhgrGZ, token: 4342sd, proxy: reverse, server: external}
      - {username: x3451, password: secret, token: abcde, proxy: redirect}
```


I know that you set  `xtream_skip_live_direct_source` and  `xtream_skip_video_direct_source` to `true`.

If not you should, because the player can access the direct-source attribute and ignore the server info.


If you use `https`, you need a ssl terminator,  `m3u-filter` does not support https traffic.
