### DISCUSSION TITLE
Xtream proxy redirect http/https mixing issues

### DISCUSSION THREAD

**Discussion by haroldthegray** [euzu/tuliprox#36] [Q&A] [answered]
Not sure if this is a bug/feature-request/dumb-user problem...

I have an instance that I'm reverse proxy-ing through nginx. nginx provides https and gets back to m3u-filter's http service.
No problem.
I am filtering Xtream playlists on both sides.
No problem.
Trying to open a stream?
Problem.

I am using proxy-redirect Xtream inside m3u-filter.
Calling up a stream hits https://m3u.mynginx.com/live/user/pass/0000001.ts as expected, which redirects to my source input **https**://XXstreamsXX.com:80/live/XXuserXX/XXpassXX/0000001.ts _mostly_ as expected, EXCEPT it is **HTTPS** whereas my source is **HTTP**.

I'm guessing that the protocol is being stripped at some point when the redirection URL is built, but I figure strictly adhering to the input URL as defined might be best if that is possible?

source.yml snippet for clarity
```yaml
sources:
  - inputs:
      - enabled: true
        type: xtream
        headers:
          User-Agent: "..."
          Accept: application/json
          Accept-Encoding: gzip
        url: 'http://XXstreamsXX:80'
        username: XXuserXX
        password: XXpassXX
```

**Comment by euzu** [comment]
@haroldthegray I will take a look at this.
But i am busy this weekend.

**Reply by haroldthegray** [reply]
Thank you. Hope your busy weekend is fun and not chores.

**Reply by euzu** [reply, marked as answer]
@haroldthegray there is a debug output  `debug!("Redirecting stream request to {}", stream_url);`
Can you test it with loglevel debug and tell me the debug output uses https?

**Reply by haroldthegray** [reply]
Yep... this was a dumb-user (me) problem. Higher level nginx proxy config I setup was rewriting. Sorry about the confusion.

While we're here talking about user-error...
How should I include two different xtream sources in the YAML?

```YAML
sources:
  - inputs:
      - enabled: true
        type: xtream
        headers:
          User-Agent: "..."
          Accept: application/json
          Accept-Encoding: gzip
        url: 'http://XXstreamsXX:80'
        username: XXuserXX
        password: XXpassXX
      - enabled: true
        type: xtream
        headers:
          User-Agent: "..."
          Accept: application/json
          Accept-Encoding: gzip
        url: 'http://YYotherstreamsYY:80'
        username: YYuserYY
        password: YYpassYY
    targets:
      - name: base
        output:
          - type: xtream
        filter: .....
```

According to the logs, this pulls in the source xtream info just fine, but when it comes to making it available at the target, everything gets the first source's URL and credentials. Proper stream SID in the URL, just wrong source for redirect.
