### DISCUSSION TITLE
Set the epg_channel_id?

### DISCUSSION THREAD

**Discussion by zero-well** [euzu/tuliprox#48] [Q&A]
Is it possible to set the epg_channel_id/tvg_id?

my epg is from a different source and the epg id doesn't line up so I'd like to override it. I've tried `tvg_id`, `chno`, `epg_channel_id` to no avail. Any suggestions?

```
mappings:
  templates:
  mapping:
    - id: espn
      mapper:
        - pattern: 'Name ~ "ESPN \(East Server\)"'
          attributes:
            name: ESPN
            title: ESPN
            epg_channel_id: espn.us
```

**Comment by zero-well** [comment]
I found `id:` in the readme, but when I set `id` I get this error in the logs and the channel just doesn't show up anymore:


```
m3u-filter  | [2024-04-05T16:52:18Z ERROR m3u_filter::processing::playlist_processor] Channel does not have an id: ESPN
```

```
mappings:
  templates:
  mapping:
    - id: espn
      mapper:
        - pattern: 'Name ~ "ESPN \(East Server\)"'
          attributes:
            name: ESPN
            title: ESPN
            id: espn.us
```

**Reply by zero-well** [reply]
In the debug logs I can see it was set though:


```
m3u-filter  | [2024-04-05T16:54:44Z DEBUG m3u_filter::model::mapping] Property id set to espn.us
```

**Reply by zero-well** [reply]
![image](https://github.com/euzu/m3u-filter/assets/160749165/d1ea410b-63b0-4ef3-a460-871d32c91378)

It's also a little unclear to me why you have trailing commas in your README? Was that a mistake? Either way it doesn't make a difference to the error.

**Reply by euzu** [reply]
@RohirrimRider  the trailing commas are wrong. It is a mistake in the readme.

**Reply by euzu** [reply]
@RohirrimRider i cant follow your description of the problem. You have a different epg provider and want to match it with your playlist?
And when you set the id of a channel to an id in the epg list, the channel disappears?

**Reply by zero-well** [reply]
Yes. When I use the config above and try to set the `id:` parameter I get the error that the channel does not have an `id` like this:

```
          attributes:
            name: ESPN
            title: ESPN
            id: espn.us
```

I get the error in the logs saying the channel does not have an id and then the channel does not exist in any output.

**Comment by euzu** [comment]
Ok I'll take a look at this.

**Comment by euzu** [comment]
@RohirrimRider  i know the reason not the id, the epg_channel_id is used.

Solution: Enable epg_channel_id mapping

**Comment by euzu** [comment]
@RohirrimRider i have added the changes to the `feature/m3u_reverse_proxy` branch. 
You need to map the `epg_channel_id` (or `epg_id`), not the `id`

**Reply by zero-well** [reply]
Okay I'll try it out now

**Reply by zero-well** [reply]
It still doesn't work for me on `feature/m3u_reverse_proxy` but the m3u does show the reverse proxy link now.

**Reply by euzu** [reply]
@RohirrimRider  did you  map the `epg_channel_id` to the same as in the `epg.xml` file ? 
The EPG Xml file has a tag `channel` with an attribute  `id` =>  `<channel id="espn.us">`

I am matching this `id` with the  `epg_channel_id`attribute.

You need to map this attribute to `espn.us`  in the `mapping.yml`

If you did this and it is not working, then i need to investigate more in this issue.

**Reply by zero-well** [reply]
Yes the epg.xml has `<channel id="espn.us">` and I mapped `epg_id` and `epg_channel_id` and in the `get_live_streams` the epg_channel_id is `null`

**Reply by euzu** [reply]
`epg_id` is an alias for `epg_channel_id`  you only need to set one.

**Comment by euzu** [comment]
> Yes the epg.xml has `<channel id="espn.us">` and I mapped `epg_id` and `epg_channel_id` and in the `get_live_streams` the epg_channel_id is `null`

@RohirrimRider ok i look into it.

**Comment by zero-well** [comment]
Yes I just mean I tried both

**Comment by euzu** [comment]
@RohirrimRider  how does your client fetch the epg data ?  over the `get_short_epg` action from `player_api.php` ?

**Comment by zero-well** [comment]
Hmm I was just using curl to fetch it all. I can try that endpoint though

**Reply by euzu** [reply]
I dont understand,  aren't you using an iptv player  on your device?  When you say the epg data is not available, i thought your iptv player did not show the epg data. my question is, how does the player fetch the epg data.

**Reply by zero-well** [reply]
The epg_url is in the input:

```
sources:
  - inputs:
      - enabled: true
        type: xtream
        persist: 'playlist_1_1{}.m3u'
        headers:
          User-Agent: *user_agent
        url: 'http://myservice.com:8000'
        epg_url: 'https://epg.tvnow.best/utc.xml'
```

I'm not using a client for testing I'm just curling the endpoints with:

`curl 'http://localhost:8901/player_api.php?username=MYUSER&password=MYPASS&action=get_short_epg`

This gives me 

```
{
    "epg_listings": []
}
```

When I `curl 'http://localhost:8901/player_api.php?username=MYUSER&password=MYPASS&action=get_live_streams`

The stream for the channel I'm trying to map has a null epg_channel_id. Is that what I'm supposed to see?

**Reply by euzu** [reply]
Your url is wrong.  get_short_epg  needs a stream_id,   
The Problem is, i dont know what the client sends to the server, the stream_id or the epg_channel_id ? 

Currently i am sending the stream_id from the request as is to the server. Which is wrong in our case, because i need to read the epg data from the disc and not from the provider.
This part is currently missing, need to implement it.

I have changed the code so that you get BadRequest when you forget the stream_id now. 
Update from master please.

**Reply by zero-well** [reply]
Okay I'll have to check with my app. I'm using ChannelsDVR so it's not using the XC api. It's using the m3u and xml links directly. It's trying to match up the tvg-id with the channel-id in the epg xml I believe.

**Reply by zero-well** [reply]
```
m3u-filter  | [2024-04-06T14:34:00Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /m3u?username=***&password=*** HTTP/1.1" 200 204220 "-" "Go-http-client/1.1" 0.001431
m3u-filter  | [2024-04-06T14:34:00Z INFO  actix_web::middleware::logger] 172.18.0.6 "GET /epg?username=***&password=*** HTTP/1.1" 200 322622 "-" "Mozilla/5.0 ChannelsDVR+XMLTV/1.0" 0.001099
```

Here are the HTTP calls from Channels DVR

**Comment by euzu** [comment]
Ok thay means the complete epg.xml file is fetched.
The difference between m3u and xtream is,
m3u fetches the complete epg file and matches the chanmels, xtream requests for each channel the epg info.

But the epg file should be available if the input has an epg_url.

If you dont have epg information, it could be a problem with the id matching.

**Reply by zero-well** [reply]
Okay I see what you mean now. I understand the problem. Thank you

**Comment by zero-well** [comment]
![image](https://github.com/euzu/m3u-filter/assets/160749165/d7406829-7798-4d5a-8bba-eaf3257797ed)
![image](https://github.com/euzu/m3u-filter/assets/160749165/018a7977-4f38-494e-9fce-e6382cadbb1b)
![image](https://github.com/euzu/m3u-filter/assets/160749165/ccd118d1-89ec-4ea3-805d-e7f970277a81)

It's still not mapping though. When I do action=get_live_streams the epg_channel_id is still wrong. It shows the original channel_id. is it possible that you are loading the epg associated with the xtream api? My xc epg doesn't provide any program data, but it returns channel information. I want the epg_url to overwrite the xc api source.

**Reply by euzu** [reply]
@RohirrimRider is this problem with the latest release solved ?

**Comment by kruska7** [comment]
@euzu I also cannot get mapping epg_channel_id to work.

My mapping.yml:

```
mappings:
  templates:
  mapping:
    - id: SVTB
      mapper:
        - pattern: 'Name ~ ".*"'
          attributes:
            epg_channel_id: TEST
```

In source targets:

```
  targets:
    - name: foo
      output:
        - type: xtream
      filter: "!DK_CHAN!"
      mapping:
        - SVTB
      options: {ignore_logo: false, xtream_skip_live_direct_source: true, xtream_skip_video_direct_source: true}
```

When I check in the created live.db (I don't know where else to confirm the changes) all channels have their original epg_channel_id as provided by provider, none has changed. With the above mapping all should have id TEST.
