### DISCUSSION TITLE
Possible to use environment variables in yaml files?

### DISCUSSION THREAD

**Discussion by zero-well** [euzu/tuliprox#49] [Q&A] [answered]
Specifically in the api-proxy.yml there are username/passwords. Can we use environment variables instead of hard coding?

**Comment by euzu** [comment, marked as answer]
I have added  env variable support to  `api-proxy.yml`     for `username`, `password` and `token`

```
user:
- target: simple
  credentials:
  - username: ${env:M3UF_USR_ME}
    password: ${env:M3UF_PWD_ME}
    token: ${env:M3UF_TKN_ME}
    proxy: redirect
    server: null
```
For this example you need to define environment variables  
  - M3UF_USR_ME
  - M3UF_PWD_ME
  - M3UF_TKN_ME


The var name  should match pattern: `[a-zA-Z_][a-zA-Z0-9_]+`           starts with `letter` or `underscore` followed by `letter` or `underscore` or `number`
