### DISCUSSION TITLE
Can not get a chno Mapping to work

### DISCUSSION THREAD

**Discussion by jamesarbrown** [euzu/tuliprox#66] [Q&A] [answered]
Hi,

My M3u is not being populated with a chno. Is this because it does not exist in the original m3u? How can it be forced to be added to the m3u? The name attribute is working.

```
mappings:
  mapping:
    - id: UKTV
      match_as_ascii: true
      mapper:
        - pattern: 'Url ~ ".*166.ts"'
          attributes:
            name: 'xyz |SD|'
            chno: '200'
          assignments:
             title: name
```
