### DISCUSSION TITLE
Hang after startup? (docker)

### DISCUSSION THREAD

**Discussion by Metathesus** [euzu/tuliprox#80] [Q&A] [answered]
Hello,
After struggeling to have valid configuration files (the source file in config folder of github have "output:" missing and have misleading me), I have finally be able to start the container **using the provided docker-compose file**.

But, I can't go further, **I'm not able to access to the web-UI** (la connection a échoué - Firefox ne peut établir de connexion avec le serveur à l’adresse 192.168.1.254:8901)

Log of the container stop at "starting in Actix runtime", I don't know if it's OK!
```
[2024-08-28T16:11:33Z INFO  m3u_filter] Version: 2.0.3
[2024-08-28T16:11:33Z INFO  m3u_filter] Current time: 2024-08-28 18:11:33
[2024-08-28T16:11:33Z INFO  m3u_filter] Working dir: "/"
[2024-08-28T16:11:33Z INFO  m3u_filter] Config dir: "/config"
[2024-08-28T16:11:33Z INFO  m3u_filter] Config file: /config/config.yml
[2024-08-28T16:11:33Z INFO  m3u_filter] Source file: /config/source.yml
[2024-08-28T16:11:33Z INFO  m3u_filter::utils::config_reader] Mappings File: /config/mapping.yml
[2024-08-28T16:11:33Z ERROR m3u_filter::utils::config_reader] cant read api-proxy-config file: missing field `server`
[2024-08-28T16:11:33Z WARN  m3u_filter::utils::config_reader] cant read api_proxy_config file: /config/api-proxy.yml
[2024-08-28T16:11:33Z INFO  m3u_filter] Server running: http://127.0.0.1:8901
[2024-08-28T16:11:33Z INFO  m3u_filter::api::main_api] Web root: "/web"
[2024-08-28T16:11:33Z INFO  actix_server::builder] starting 4 workers
[2024-08-28T16:11:33Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
```
I'have made tests with a complete api_proxy_config file and an empty one (like in log) and it doesn't change anything.

config.yml seems OK:
```
api:
  host: 127.0.0.1
  port: 8901
  web_root: /web
working_dir: /
threads: 0
update_on_boot: false
# sec  min   hour   day of month   month   day of week   year
schedule: "0  0  4  *  *  *  *"
web_ui_enabled: true
web_auth:
  enabled: false
  secret: PasswordForAFutureEnabledAuth
  issuer: m3u_filter
  userfile: user.txt
```

Source:
```
sources:
  - inputs:
      - enabled: false
        type: xtream
        url: 'http://largeplaylist.url'
        username: Moi
        password: MonMotDePasse
        headers:
          User-Agent: "Mozilla/5.0 (AppleTV; U; CPU OS 14_2 like Mac OS X; en-us) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
          Accept: application/json, application/xml
          Accept-Encoding: gzip
      - enabled: true
        type: xtream
        url: 'http://petiteplaylist.url:8080'
        username: EncoreMoi
        password: MonAutreMotDePasse
        headers:
          User-Agent: "Mozilla/5.0 (AppleTV; U; CPU OS 14_2 like Mac OS X; en-us) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
          Accept: application/json, application/xml
          Accept-Encoding: gzip
          
          
    targets:
      - name: plxtream
        output:
          - type: xtream
        options: 
          ignore_logo: true 
          xtream_skip_live_direct_source: false
          xtream_skip_video_direct_source: false
          xtream_skip_series_direct_source: false
        filter: 'Group ~ "^FR| .*]"'
        sort:
          groups:
            order: asc
        mapping:
          - France TNT
```

The mapping file is the same as yours (càd parfait pour les chaines françaises!!!)

Thanks by advance for your help, I have probably missed or misunderstand something.

P.S: J'espère vraiment à arriver à le faire fonctionner, ça répond exactement à mes besoins! (byebye threadfin?)

**Comment by euzu** [comment, marked as answer]
I am not sure but i think, if the server inside the container is bound to 127.0.0.1, the mapped port on the host 8901 will not work because the service is not accessible on the container's external network interface; it's only accessible on the container's loopback interface 127.0.0.1.

I have  0.0.0.0  instead of 127.0.0.1.

Can you try and tell me.  Btw you should have a valid api_proxy.yml.

**Reply by Metathesus** [reply]
Thank you!
0.0.0.0 was the answer!
Yes a valid proxy have to be there to avoid a "javascript error" on the web UI!
I have now to properly configure the ports in my docker-compose.yml file to ensure that external connections are correctly routed to the proxy inside the container.

**Comment by Metathesus** [comment]
Hi
I'm now NOT able to make the "proxy" works.

1) Source seems OK and processing the m3u too:
```
[2024-08-29T10:49:14Z DEBUG m3u_filter::processing::playlist_processor] Decoded FR| MEZZO FHD for matching to FR| MEZZO FHD
[2024-08-29T10:49:14Z INFO  m3u_filter::processing::playlist_processor] {"stats": {"name": https://myprovider.com/m3u/threadfin.m3u?username=MYUSERNAME&password=MYPASSWORD, "type": m3u, "errors": 0, "raw": {"groups": 1, "channels": 68}, "processed": {"groups": 1, "channels": 68}}}
```

2) api-proxy.yml
```
server:
- name: default
  protocol: http
  host: 192.168.1.254
  http_port: '11001'
  https_port: '11443'
  rtmp_port: '1953'
  timezone: Europe/Paris
  message: Welcome to m3u-filter
- name: domain
  protocol: https
  host: mycustomtv.mydomain.com
  http_port: '80'
  https_port: '443'
  rtmp_port: '1953'
  timezone: Europe/Paris
  message: Welcome to m3u-filter
user:
- target: Playlist_France_M3U
  credentials:
  - username: MyUsername01
    password: MyBeautifulPassword
    token: null
    proxy: redirect
    server: default
  - username: MyUsername02
    password: MyBeautifulPassword
    token: null
    proxy: redirect
    server: domain

```

3) Docker Compose
```
services:
  m3u-filter:
    container_name: m3u-filter
    image: ghcr.io/euzu/m3u-filter:latest
    working_dir: /
    volumes:
      - /mnt/Docker/m3u_filter/config:/config
      - /mnt/Docker/m3u_filter/data:/data
      - /mnt/Docker/m3u_filter/backup:/backup
      - /mnt/Docker/m3u_filter/downloads:/downloads
    environment:
      - TZ=Europe/Paris
      - M3U_FILTER_LOG=debug
    ports:
      #Local access
      - 11000:11000
      - 11001:11001
      - 1953:1953
      #Distant Access
      - 11080:80
      - 11443:443
    restart: unless-stopped
```

4) Accessing through http://192.168.1.254:11001/get.php?username=MyUsername01&password=MyBeautifulPassword give me a connection failed (la connexion a échoué, Firefox ne peut établir de connexion avec le serveur à l’adresse 192.168.1.254:11001.).
   I have nothing in the docker logs showing the attempted connection (debug mode)
   In the API-proxy.yml, I have tested with 192.168.1.254 (docker server) and 0.0.0.0, but none oh them working.

5) After clicking the START update button, I was thinking that I will find something in the "data" folder, but it remain empty.
   Where are the temporary or persistant m3u?
 ![[Pasted image 20240829132433.png]]

6) Source.yml
```
sources:
  - inputs:
      - enabled: true
        type: m3u
        url: 'https://myprovider.com/m3u/threadfin.m3u?username=MYUSERNAME&password=MYPASSWORD'
        persist: playlist_theadfin_{}.m3u     
        
    targets:
      - name: Playlist_France_M3U
        enabled: true
        output:
          - type: m3u
        filter: 'Group ~ "^FR.*"'
        sort:
          groups:
            order: asc
        mapping:
          - France TNT
```

7) What should I find in the Data folder?

Hope you can help me!
Thanks by Advance
