### DISCUSSION TITLE
Auto assign channel number

### DISCUSSION THREAD

**Discussion by wanderleyteixeira** [euzu/tuliprox#85] [Ideas]
Hello. It would be nice to assign a starting channel number and increment it automatically for mapped channels. 
The example below would auto increment the `start_chno` for each channel listed in that `id`. Also, if you redefine a `chno` in the `attributes` then subsequent channels will just increment or set something based on the group name. 
Pattern Sport would start at 2000, Sport1 2001, New 3000, New1 3001, etc
Thoughts?

```
mappings:
  mapping:
    - id: CA-TV
      start_chno: '2000'
      mapper:
        - pattern: 'Name ~ "!start!.*Sport!quality!"'
          attributes:
            group: 'Sport'
            name: 'ABC |HD|'
        - pattern: 'Name ~ "!start!.*Sport1!quality!"'
          attributes:
            group: 'Sport'
            name: 'SSS |HD|'
        - pattern: 'Name ~ "!start!.*New!quality!"'
          attributes:
            group: 'News'
            name: 'XYZ |HD|'
            chno: 3000
        - pattern: 'Name ~ "!start!.*New1!quality!"'
          attributes:
            group: 'News'
            name: 'XYZ |HD|'
```

**Comment by euzu** [comment]
@wanderleyteixeira  what I could imagine is that you enter a start number for a group and the channels are then numbered consecutively.
The problem is then to avoid overlapped channel numbers, if you dont give all groups a start number.

I need to think about this.

**Reply by wanderleyteixeira** [reply]
Yes, definitely something to consider. I'd still take the risk of overlaps rather than numbering 50+ channels. Thank you for taking into consideration. `m3u-filter` is great.

**Comment by euzu** [comment]
@wanderleyteixeira  i have implemented a counter mechanism.


pushed to branch [counter](https://github.com/euzu/m3u-filter/tree/feature/channel_numbering)

Please can you test and confirm?

Each mapping can have a  list of counter.

A counter has the following fields:
- `filter`: filter expression
- `value`: an initial start value
- `field`: `title`, `name`, `chno`
- `modifier`: `assign`, `suffix`, `prefix`
- `concat`: is _optional_ and only used if `suffix` or `prefix` modifier given.

```yaml
mapping:
  - id: simple
    match_as_ascii: true
    counter:
      - filter: '....some filter....'
        value: 9000
        field: chno
        modifier: assign
    mapper:
      - <Mapper definition>
```

you can also do something like this


```yaml
mapping:
  - id: simple
    match_as_ascii: true
    counter:
      - filter: '....some filter....'
        value: 9000
        field: title
        modifier: suffix
        concat: " - "
    mapper:
      - <Mapper definition>
```
