### DISCUSSION TITLE
Combining filter (exclude issue)

### DISCUSSION THREAD

**Discussion by Metathesus** [euzu/tuliprox#97] [General]
I've downloaded the last binary you provide me today (last issue).
My source is a large xTream

```
    targets:
      - name: Playlist_France
        output:
          - type: xtream
        enabled: true
        options: 
          ignore_logo: true 
          xtream_skip_live_direct_source: false
          xtream_skip_video_direct_source: false
          xtream_skip_series_direct_source: false
        filter: "!FRANCE_FULL! AND !EXCLUDE_FOR_GLOBAL!"
        sort:
          groups:
            order: asc
        rename:
          - field: group
            pattern: ^EU \| FRANCE(.*)
            new_name: FRANCE
            
      - name: Playlist_France_TV
        output:
          - type: m3u
          - type: xtream
        enabled: true
        options: 
          ignore_logo: true 
          xtream_skip_live_direct_source: false
          xtream_skip_video_direct_source: false
          xtream_skip_series_direct_source: false
        filter: "!FRANCE_TV! AND !EXCLUDE_FOR_GLOBAL!"
        sort:
          groups:
            order: asc
        rename:
          - field: group
            pattern: ^EU \| FRANCE(.*)
            new_name: FRANCE


templates:
  - name: FRANCE_TV
    value: 'Group ~ "^EU \| FRANCE.*"'
    
  - name: FRANCE_VIDEOS
    value: 'Group ~ "^VOD \| FR.*" OR Group ~ "\[FR\].*"'
    
  - name: FRANCE_SERIES
    value: 'Group ~ "^SRS \| FR.*"'
    
  - name: FRANCE_FULL
    value: '!FRANCE_TV! OR !FRANCE_VIDEOS! OR !FRANCE_SERIES!'   
    
  - name: SD
    value: 'Group ~ ".* LQ.*" OR Title ~ ".* LQ.*" OR Group ~ ".* SD.*" OR Title ~ ".* SD.*"'
    
  - name: HD
    value: 'Group ~ ".* HD.*" OR Title ~ ".* HD.*"'
    
  - name: SPORT_GROUPS 
    value: 'Group ~ "(?i).*sport.*" OR Group ~ "(?i).*DAZN.*" OR Group ~ "(?i).*EQUIPE.*"'
    
  - name: SPORT_TITLES
    value: 'Title ~ "(?i).* sport.*"'
    
  - name: OTHER_GROUPS
    value: 'Group ~ "DOM TOM.*" OR Group ~ "(?i).*PLUTO.*"'
    
  - name: OTHER_TITLES
    value: 'Title ~ "(?i).*GOLD.*" OR Title ~ "#####.*"'
 
  - name: EXCLUDE_FOR_GLOBAL
    value: 'not(!SD! OR !HD! OR !SPORT_GROUPS! OR !OTHER_GROUPS! OR !OTHER_TITLES!)'
```

"Playlist_France_TV" is OK, "EXCLUDE FOR GLOBAL" is applied
![France_TV](https://github.com/user-attachments/assets/c0a603ee-4ee5-4a57-b8d4-16b729d32a4c)

"Playlist_France" is not OK, "EXCLUDE FOR GLOBAL" is not applied
![France](https://github.com/user-attachments/assets/6a39b806-fd8e-4def-b461-6e2fc27e3917)

As you can see the live.db is bigger in "Playlist_France"  than the "Playlist_France_TV", I was waiting for the same live list in both cases.

Can you help me to understand why adding VOD and series break the filter?

Thanks by advance.
