### DISCUSSION TITLE
Provider Group/Channel Order Passthrough

### DISCUSSION THREAD

**Discussion by solohpgh** [euzu/tuliprox#98] [Q&A] [answered]
Hey All.

Can someone tell me if there is a switch that I need to use (or even if it is possible), to ensure that when using m3u-filter in reverse proxy mode, that the output order of the groups and the channels, remain the same as the providers?

So far I have tried a combination of things:
 - source template set to url or group or name
 - source target - sorting omitted from config

However, anything I have tried so far, the output from the xtream api sorts the groups alphabetically.
(The channels remain in the order of the provider, so that is fine and wanted)

Any suggestions that I can try?

**Comment by euzu** [comment, marked as answer]
Hi @solohpgh, 

this is not possible. 

The only solution is to define the sorting yourself,

Sorting can be done by using the sort part of input target: 

You can sort groups or channels inside groups. You can sort  ASC or DESC  or define a sequence with the channel names.

```yaml
  targets:
  - name: test
    output:
      - type: m3u
    filter: "!TEST_FILTER!"
    options: {ignore_logo: true}
    sort:
      groups:
        order: asc
      channels:
        - { field: name,  group_pattern: '^FR.*',  order: asc }
        - field: name
          group_pattern: '^News'
          order: asc
          sequence:
            - CNN
            - BBC
            - NTV
    mapping:
```

If you want to keep the provider's order, we will need to implement that.

The problem is that multiple sources can be combined, and channels can be mapped to new groups. This means the result could be completely different from the original source.

The group names might be different, the channel names could change, and channels from different sources might be mixed into a new group.

How would you map the original to the result in this case?
I can't think of a solution for this.
